name: ndc-prometheus
version: "${CLI_VERSION}"
shortDescription: "CLI plugin for Hasura Prometheus data connector"
homepage: https://github.com/hasura/ndc-prometheus
hidden: true
platforms:
  - selector: darwin-arm64
    uri: "https://github.com/hasura/ndc-prometheus/releases/download/${CLI_VERSION}/ndc-prometheus-darwin-arm64"
    sha256: "${MACOS_ARM64_SHA256}"
    bin: "ndc-prometheus"
    files:
      - from: "./ndc-prometheus-darwin-arm64"
        to: "ndc-prometheus"
  - selector: linux-arm64
    uri: "https://github.com/hasura/ndc-prometheus/releases/download/${CLI_VERSION}/ndc-prometheus-linux-arm64"
    sha256: "${LINUX_ARM64_SHA256}"
    bin: "ndc-prometheus"
    files:
      - from: "./ndc-prometheus-linux-arm64"
        to: "ndc-prometheus"
  - selector: darwin-amd64
    uri: "https://github.com/hasura/ndc-prometheus/releases/download/${CLI_VERSION}/ndc-prometheus-darwin-amd64"
    sha256: "${MACOS_AMD64_SHA256}"
    bin: "ndc-prometheus"
    files:
      - from: "./ndc-prometheus-darwin-amd64"
        to: "ndc-prometheus"
  - selector: windows-amd64
    uri: "https://github.com/hasura/ndc-prometheus/releases/download/${CLI_VERSION}/ndc-prometheus-windows-amd64.exe"
    sha256: "${WINDOWS_AMD64_SHA256}"
    bin: "ndc-prometheus.exe"
    files:
      - from: "./ndc-prometheus-windows-amd64.exe"
        to: "ndc-prometheus.exe"
  - selector: linux-amd64
    uri: "https://github.com/hasura/ndc-prometheus/releases/download/${CLI_VERSION}/ndc-prometheus-linux-amd64"
    sha256: "${LINUX_AMD64_SHA256}"
    bin: "ndc-prometheus"
    files:
      - from: "./ndc-prometheus-linux-amd64"
        to: "ndc-prometheus"
