include:
  - path: ./compose.base.yaml
  - path: ./tests/engine/compose.yaml
services:
  jaeger:
    image: jaegertracing/all-in-one:1.60
    restart: always
    ports:
      - 16686:16686
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
