# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-prometheus/main/jsonschema/configuration.json
connection_settings:
  url:
    variable: CONNECTION_URL
generator:
  metrics:
    enabled: true
    include: []
    exclude: []
metadata:
  metrics: {}
  native_operations:
    queries: {}
