# yaml-language-server: $schema=https://raw.githubusercontent.com/hasura/ndc-prometheus/main/jsonschema/configuration.json
connection_settings:
  url:
    env: CONNECTION_URL
generator:
  metrics:
    enabled: true
    behavior: merge
    include: []
    exclude: []
    exclude_labels: []
    start_at: "2024-01-01T00:00:00Z"
metadata:
  metrics: {}
  native_operations:
    queries: {}
runtime:
  flat: false
  promptql: false
  unix_time_unit: s
  disable_prometheus_api: false
  format:
    timestamp: unix
    value: float64
    nan: "NaN"
    inf: "+Inf"
    negative_inf: "-Inf"
